version: '3'
services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "${HOST_PORT}:8081"
    environment: 
      DB_HOST: "jdbc:postgresql://${IP}:5432/seller_panel"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"