spring:
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/seller-panel}
    username: ${DB_USER:default}
    password: ${DB_PASS:default}
    show-sql: true
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug
    com:
      seller:
        panel: info
server:
  port: ${SERVER_PORT:8081}