spring:
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/seller-panel}
    username: ${DB_USER:default}
    password: ${DB_PASS:default}
    show-sql: true
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: abd
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            starttls: true
flyway:
  locations: classpath:/db/migration
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug
    com:
      seller:
        panel: info
server:
  port: ${SERVER_PORT:8081}
---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:seller-panel;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
flyway:
  locations: classpath:/db/migration